# Generated by Django 5.2.1 on 2025-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listsing',
            new_name='Listing',
        ),
    ]
